### ISSUE TITLE
Sudden traceback: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by thorsten-panknin** [edsu/feediverse#28]
I had been running Feediverse for months without fault, but since today, I am getting a traceback. How can I possibly fix this?

```
Traceback (most recent call last):
  File "/home/xxx/.local/bin/feediverse", line 11, in <module>
    load_entry_point('feediverse==0.2.0', 'console_scripts', 'feediverse')()
  File "/home/xxx/.local/lib/python3.6/site-packages/feediverse.py", line 51, in main
    config = read_config(config_file)
  File "/home/xxx/.local/lib/python3.6/site-packages/feediverse.py", line 107, in read_config
    if 'updated' in cfg:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by thorsten-panknin** [comment]
Oh, I may have an idea what the cause might be. I exceeded my quota at my web hoster and write access was on halt until I made some room. I'll check into that.

**Comment by thorsten-panknin** [comment]
The config file is empty. I'll re-install / re-setup.
